### ISSUE TITLE
Commit History SHA Buttons Look A Bit Off

### ISSUE THREAD

**Issue by zekefarwell** [daattali/oldschool-github-extension#17]
Just noticed the split buttons don't look so great in the history view.  Maybe just reducing the double line between them down to a single is all that's needed.  I haven't looked closely enough to be sure.  Screenshots included for reference.

**Classic UI** (from wayback machine)
<img width="1003" alt="Screen Shot 2020-06-26 at 12 37 04 AM" src="https://user-images.githubusercontent.com/281482/85882183-d68c5380-b7ac-11ea-9ce6-46add7de4c49.png">

**Current Default UI**
<img width="997" alt="Screen Shot 2020-06-26 at 12 38 46 AM" src="https://user-images.githubusercontent.com/281482/85882193-dab87100-b7ac-11ea-88af-17763763b11f.png">

**Old School Github Enabled**
<img width="987" alt="Screen Shot 2020-06-26 at 12 39 30 AM" src="https://user-images.githubusercontent.com/281482/85882212-e0ae5200-b7ac-11ea-8c33-5df08d534dc9.png">

**Comment by daattali** [comment]
Same is happening with the Raw/Blame buttons on file view.

I briefly tried to address that yesterday but gave up pretty quickly because I thought nobody else would notice :p

What I tried is setting the border-right to 0 on the first `.BtnGroup-item` but then when you hover over it, the border does need to return and I got distracted by other issues and never ended up going back to this.
