### ISSUE TITLE
The extension has stopped working

### ISSUE THREAD

**Issue by DesertStars** [daattali/oldschool-github-extension#40]
The extension doesn't work for me anymore, Github's UI is now back to the new version.

Browser is Firefox 85.0.1

**Comment by daattali** [comment]
I can't reproduce. On both my chrome and firefox (I'm on version 84) it's still working

**Comment by zekefarwell** [comment]
Are you talking about this?
![Screenshot 2021-02-23 220008](https://user-images.githubusercontent.com/281482/108941173-9c689f80-7622-11eb-9080-5d06881c0f47.jpg)

Looks to me like the extension is mostly working, but I am seeing that the repo header width is no longer restricted like it was before on wider screens.

**Comment by huhenU** [comment]
To me it looks like Github has renamed something to do with the header. 
Replacing `bg-gray-light` in the userstyle in the part where it's moving the header to the middle with `color-bg-secondary` did the trick for me. (On first sight at least. I'm not sure if they changed anything else or if that's the ideal solution tho.)

**Comment by DesertStars** [comment]
> Are you talking about this?
> ![Screenshot 2021-02-23 220008](https://user-images.githubusercontent.com/281482/108941173-9c689f80-7622-11eb-9080-5d06881c0f47.jpg)
> 
> Looks to me like the extension is mostly working, but I am seeing that the repo header width is no longer restricted like it was before on wider screens.

Yeah, I should have been more clear, I'm talking about the header.

**Comment by daattali** [comment]
Ah ok, thanks for reporting! Being on a laptop that didn't immediately jump out

**Comment by TheKodeToad** [comment]
I don't know whether this project is still maintained, but this issue has returned in 2022, probably due to the tabs having further tweaks. There is also an issue with a border appearing below the active tab, and a bit too much spacing below it, and a hover effect which I don't think was present in older GitHub versions.

![image](https://user-images.githubusercontent.com/57493648/183652221-3bf5f54d-f6f2-4797-a572-d67ac0c8bcff.png)
